version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web
    restart: unless-stopped
    tty: true
    env_file: .env
    environment:
      - MONGO_USERNAME=$MONGO_USERNAME
      - MONGO_PASSWORD=$MONGO_PASSWORD
      - MONGO_HOSTNAME=mongodb
      - MONGO_PORT=$MONGO_PORT
      - MONGO_DB=$MONGO_DB
    ports:
      - 5000:5000
      - 3000:3000
    volumes:
      - .:/home/node/app
#      - node_modules:/home/node/app/node_modules
    networks:
      - app-network
#    command: ./wait-for.sh db:27017 -- npx nodemon app.js
    depends_on:
      - mongodb
    command: npx nodemon app.js

  mongodb:
    image: mvertes/alpine-mongo
    container_name: mongodb
    restart: unless-stopped
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
    volumes:
      - dbdata:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
#  node_modules: